# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/154a938f-641d-4574-803b-e8b696178d7f";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  boot.initrd.luks.devices."primarycrypt".device = "/dev/disk/by-uuid/d35b708d-2772-46d6-bcdc-15a266441292";

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/154a938f-641d-4574-803b-e8b696178d7f";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/154a938f-641d-4574-803b-e8b696178d7f";
      fsType = "btrfs";
      options = [ "subvol=persist" ];
    };

  fileSystems."/games" =
    { device = "/dev/disk/by-uuid/a759e204-b44c-4324-8298-3f464aec9175";
      fsType = "btrfs";
      options = [ "subvol=games" ];
    };

  boot.initrd.luks.devices."secondarycrypt".device = "/dev/disk/by-uuid/fc081a4e-1fde-42fa-bc7c-521e47283af1";

  fileSystems."/persist/home" =
    { device = "/dev/disk/by-uuid/a759e204-b44c-4324-8298-3f464aec9175";
      fsType = "btrfs";
      options = [ "subvol=persist/home" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1DA2-FD3A";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp13s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
