{
  ff.hardware.displays = {
    test = {
      port = "DP-2";
      refreshRate = 144;
      resWidth = 2560;
      resHeight = 1440;
      ownedWorkspaces = [ 1 ];
    };
  };

  boot = {
    initrd.availableKernelModules = [
      "ahci"
      "amdgpu"
      "hid-generic"
      "nvme"
      "usbhid"
      "xhci_pci"
    ];
    kernelModules = [ "kvm-amd" ];
    kernelParams = [
      "video=DP-2:2560x1440@144"
      "video=DP-1:1920x1080@60"
      "video=HDMI-A-1:1920x1080@60"
    ];
  };
  hardware = {
    cpu.amd.updateMicrocode = true;
    graphics = {
      enable = true;
      enable32Bit = true;
    };
    enableRedistributableFirmware = true;

    # wouldnt build 04/04/2025
    #openrazer = {
    #  enable = true;
    #  users = [ "quinno" ];
    #};
    display = {
      edid = {
        enable = true;
      };
    };
    i2c.enable = true;

    fancontrol = {
      enable = true;
      config = ''
        # Configuration file generated by pwmconfig, changes will be lost
        INTERVAL=5
        DEVPATH=hwmon3=devices/pci0000:00/0000:00:01.1/0000:01:00.0/0000:02:00.0/0000:03:00.0
        DEVNAME=hwmon3=amdgpu
        FCTEMPS=hwmon3/pwm1=hwmon3/temp2_input
        FCFANS= hwmon3/pwm1=hwmon3/fan1_input
        MINTEMP=hwmon3/pwm1=40
        MAXTEMP=hwmon3/pwm1=65
        MINSTART=hwmon3/pwm1=56
        MINSTOP=hwmon3/pwm1=16
      '';
    };
  };
}
