{
  ff.hardware.displays = {
    test = {
      port = "DP-2";
      refreshRate = 144;
      resWidth = 2560;
      resHeight = 1440;
      ownedWorkspaces = [ 1 ];
    };
  };

  boot = {
    initrd.availableKernelModules = [
      "ahci"
      "hid-generic"
      "nvme"
      "usbhid"
      "xhci_pci"
    ];
    kernelParams = [
      "video=DP-2:2560x1440@144"
      "video=DP-1:1920x1080@60"
      "video=HDMI-A-1:1920x1080@60"

      # AMD optimizations
      "amd_pstate=active" # Enable active pstate for better power management
      "amd_iommu=on" # Enable IOMMU for better device isolation
      "iommu=pt" # Pass-through mode for IOMMU
      "idle=nomwait" # Improves AMD CPU power efficiency
      "pcie_aspm=force" # Force PCIe Active State Power Management
      "pci=pcie_bus_perf" # Optimize PCIe bus performance
      "transparent_hugepage=always" # Better memory management for Zen architecture
    ];
  };
  powerManagement = {
    enable = true;
    cpuFreqGovernor = "schedutil"; # Optimal for AMD Ryzen on B650
    powertop.enable = true;
    scsiLinkPolicy = "med_power_with_dipm";
  };
  hardware = {
    cpu = {
      amd = {
        updateMicrocode = true;
        sev.enable = true; # Enable AMD Secure Encrypted Virtualization
      };
    };

    # AMD chipset specific features
    amdgpu = {
      initrd.enable = true;
      opencl.enable = true;
      amdvlk.enable = true;
    };

    graphics = {
      enable = true;
      enable32Bit = true;
    };
    enableRedistributableFirmware = true;

    # wouldnt build 04/04/2025
    #openrazer = {
    #  enable = true;
    #  users = [ "quinno" ];
    #};
    display = {
      edid = {
        enable = true;
      };
    };
    i2c.enable = true;

    fancontrol = {
      enable = true;
      config = ''
        # Configuration file generated by pwmconfig, changes will be lost
        INTERVAL=5
        DEVPATH=hwmon3=devices/pci0000:00/0000:00:01.1/0000:01:00.0/0000:02:00.0/0000:03:00.0
        DEVNAME=hwmon3=amdgpu
        FCTEMPS=hwmon3/pwm1=hwmon3/temp2_input
        FCFANS= hwmon3/pwm1=hwmon3/fan1_input
        MINTEMP=hwmon3/pwm1=40
        MAXTEMP=hwmon3/pwm1=65
        MINSTART=hwmon3/pwm1=56
        MINSTOP=hwmon3/pwm1=16
      '';
    };
  };
}
