{ pkgs, ... }:
{
  # ff.hardware.displays = {
  #   test = {
  #     port = "DP-2";
  #     refreshRate = 144;
  #     resWidth = 2560;
  #     resHeight = 1440;
  #     ownedWorkspaces = [ 1 ];
  #   };
  # };

  boot = {
    initrd.availableKernelModules = [
      "ahci"
      "hid-generic"
      "nvme"
      "usbhid"
      "xhci_pci"
    ];
    kernelParams = [
      "video=DP-2:2560x1440@144"
      "video=DP-1:1920x1080@60"
      "video=HDMI-A-1:1920x1080@60"

      # AMD optimizations
      "amd_pstate=active" # Enable active pstate for better power management
      "amd_iommu=on" # Enable IOMMU for better device isolation
      "iommu=pt" # Pass-through mode for IOMMU
      "idle=nomwait" # Improves AMD CPU power efficiency
      "pci=pcie_bus_perf" # Optimize PCIe bus performance
      "transparent_hugepage=always" # Better memory management for Zen architecture

      # GPU optimizations for latency reduction
      "amdgpu.ppfeaturemask=0xffffffff" # Enable all PowerPlay features
      "amdgpu.dc=1" # Enable Display Core
      "amdgpu.dcfeaturemask=0x8" # Enable FreeSync support
      "amdgpu.freesync_video=1" # Enable FreeSync for video playback
      "amdgpu.runpm=1" # Enable runtime power management
      "amdgpu.hw_i2c=1" # Enable hardware I2C for better EDID support
    ];
  };
  powerManagement = {
    enable = true;
    cpuFreqGovernor = "performance";
    powertop.enable = true;
    scsiLinkPolicy = "max_performance";
  };

  # Prevent specific USB devices from auto-suspending
  services.udev.extraRules = ''
    # CTRL Keyboard (04d8:eed2)
    SUBSYSTEM=="usb", ATTR{idVendor}=="04d8", ATTR{idProduct}=="eed2", ATTR{power/control}="on", ATTR{power/autosuspend}="-1"

    # Razer Basilisk Ultimate Mouse (1532:0086)
    SUBSYSTEM=="usb", ATTR{idVendor}=="1532", ATTR{idProduct}=="0086", ATTR{power/control}="on", ATTR{power/autosuspend}="-1"
  '';
  hardware = {
    cpu = {
      amd = {
        updateMicrocode = true;
        sev.enable = true; # Enable AMD Secure Encrypted Virtualization
      };
    };

    # AMD chipset specific features
    amdgpu = {
      initrd.enable = true;
      opencl.enable = true;
      amdvlk.enable = true;
    };

    graphics = {
      enable = true;
      enable32Bit = true;
      extraPackages = with pkgs; [
        amdvlk
      ];
    };

    enableRedistributableFirmware = true;

    # wouldnt build 04/04/2025
    #openrazer = {
    #  enable = true;
    #  users = [ "quinno" ];
    #};
    display = {
      edid = {
        enable = true;
      };
    };
    i2c.enable = true;

    fancontrol = {
      enable = true;
      config = ''
        # Configuration file generated by pwmconfig, changes will be lost
        INTERVAL=5
        DEVPATH=hwmon3=devices/pci0000:00/0000:00:01.1/0000:01:00.0/0000:02:00.0/0000:03:00.0
        DEVNAME=hwmon3=amdgpu
        FCTEMPS=hwmon3/pwm1=hwmon3/temp2_input
        FCFANS= hwmon3/pwm1=hwmon3/fan1_input
        MINTEMP=hwmon3/pwm1=40
        MAXTEMP=hwmon3/pwm1=65
        MINSTART=hwmon3/pwm1=56
        MINSTOP=hwmon3/pwm1=16
      '';
    };
  };

  # Environment variables for better GPU and display performance
  environment.sessionVariables = {
    WLR_DRM_NO_ATOMIC = "1"; # Helps with flickering issues
    __GL_GSYNC_ALLOWED = "1"; # Enable G-Sync if available
    __GL_VRR_ALLOWED = "1"; # Enable Variable Refresh Rate
    ENABLE_VKBASALT = "1"; # Enable VkBasalt for better visuals with minimal overhead
    AMD_VULKAN_ICD = "RADV"; # Use RADV by default
    __GL_THREADED_OPTIMIZATIONS = "1"; # Enable threaded optimizations
  };
}
