---
name: Flake Lock Update
on:
  schedule:
    - cron: 0 8 * * 1,5 # Every Monday and Friday at 8:00 UTC / 3:00 EST
  workflow_dispatch: null
jobs:
  nix-lock-update:
    name: Update flake.lock
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Nix installer
        uses: DeterminateSystems/nix-installer-action@main
      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "chore: update flake.lock"
          pr-labels: |
            dependencies
            automated
